source("cachematrix.R")
x <- matrix(runif(4000000), nrow=2000, ncol=2000)
system.time(solve(x))
cx <- makeCacheMatrix(x)
system.time(cacheSolve(cx))
system.time(cacheSolve(cx))
cx$set(x)
system.time(cacheSolve(cx))
system.time(cacheSolve(cx))
